#* Build stage
FROM golang:alpine as builder

RUN apk update

WORKDIR /app

#* Instalar dependências
COPY go.mod ./
RUN go mod download

ADD . .

#* Compilar aplicação
RUN CGO_ENABLED=0 GOOS=linux go build -o main .

#* Final stage
FROM alpine:latest

WORKDIR /app

#* Instalar certificados CA para HTTPS
RUN apk --no-cache add ca-certificates

#* Copiar binário
COPY --from=builder /app/main .

EXPOSE 8000

#* Executar aplicação
CMD ["./main"]